### ISSUE TITLE
Was there an audit for the Ferro Protocol?

### ISSUE THREAD

**Issue by jedington** [blocksecteam/audit-reports#1]
![image](https://user-images.githubusercontent.com/25874804/175837189-d955fbd9-5c59-45b2-bf21-5fe5ebec9d33.png)
Didn't see this file in this repo, so it's either a falsely claimed audit, or it's missing.

**Comment by blocksecaudit** [comment]
Yes, we did. 

https://github.com/blocksecteam/audit-reports/blob/main/blocksec_ferro_v1.0_signed.pdf
